<?php

namespace FixBundle\Repository;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;
class AgendaRepository extends EntityRepository
{
    public function findProgramProf($profid){
        $query=$this->getEntityManager()
        ->createQuery("SELECT m FROM FixBundle:Agenda m WHERE m.profid=:id")->setParameter('id',$profid);
return $query->getResult();
    }


}
