<?php

namespace FixBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{

    public function findtotaleAnnonce(){
        $em = $this->getEntityManager();
        $query = $em->createQuery('select a  titre from FixBundle\Entity\Annonce a')->setParameters(array());
        return $query->execute();


    }
}
