<?php

namespace FixBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{

    public function findCategorieDQL($titre)
    {
        return $this->createQueryBuilder('c')
            ->andWhere('c.titre LIKE :titre')
            ->setParameter('titre','%'.$titre.'%')
            ->getQuery()
            ->getResult();
    }

    public function findtotale(){
       $em = $this->getEntityManager();
       $query = $em->createQuery('select c  titre from FixBundle\Entity\Categorie c')->setParameters(array());
       return $query->execute();


    }
}
