<?php

namespace FixBundle\Repository;

/**
 * EvennementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvennementRepository extends \Doctrine\ORM\EntityRepository
{
}
