<?php
/**
 * Created by PhpStorm.
 * User: MON ASUS
 * Date: 19/02/2019
 * Time: 00:35
 */

namespace FixBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRespository extends \Doctrine\ORM\EntityRepository
{

}