<?php

namespace FixBundle\Repository;

/**
 * ProfesionnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesionnelRepository extends \Doctrine\ORM\EntityRepository
{
}
