<?php

namespace FixBundle\Repository;

/**
 * programmeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class programmeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findprogramprochain($date,$id)
    {
        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT p
        FROM FixBundle\Entity\programme p
        WHERE p.date > :date and p.idagenda= :id ORDER BY p.date ASC'
        )->setParameters(array('date' => $date,'id' => $id));

        // returns an array of Product objects
        return $query->execute();
    }
}
