<?php

namespace FixBundle\Repository;

/**
 * SouscategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscategorieRepository extends \Doctrine\ORM\EntityRepository
{

    public function findtotaleSC(){
        $em = $this->getEntityManager();
        $query = $em->createQuery('select s titre from FixBundle\Entity\Souscategorie s')->setParameters(array());
        return $query->execute();


    }
}
